#!/bin/bash
set -e
set -u

control_dir="$(dirname $0)"
. "$control_dir/config"
. "$control_dir/java/functions"

export JAVA_HOME=$JAVA_HOME
export PATH=$JAVA_HOME/bin:$PATH

java_opts="$(java_opts $control_dir)"
export JETTY_OPTS="$jetty_opts"

cd $app_dir
cd jetty9

exec bash -c "
$java \
   $java_opts \
  -Djetty.home=\"$jetty_dir\" \
  -Djava.io.tmpdir=\"$app_tmp\" \
   $jetty_opts \
  -jar start.jar
"

